description: mulif_grpo_training

target:
  service: sing
  name: GenAI-Shared-UKSouth2
  workspace_name: Singularity-GenAI-WS-UKSouth2
  resource_group: singularity-genai-gpu-uksouth2

env_defaults:
  service: sing
  PRIORITY: high
  NODES: 1
  GPUS: 8
  MEM: 80


environment:
  image: mulif/ifmul:amlt
  username: 44359f3e6e864ddba0853a221be97722
  registry: 44359f3e6e864ddba0853a221be97722.azurecr.io

storage:
  output:
    storage_account_name: vigstandard
    container_name: data
    mount_dir: /mnt/data

code:
  local_dir: ./

jobs:
  - name: mulif_ms_IFTrain_linear_base_pairwise_alpha1_qwen17b_sft1
    sku: ${NODES}x${MEM}G${GPUS}
    process_count_per_node: 1
    sla_tier: Standard
    priority: high
    mpi: false
    command:
      - set -e
      - cd $$AMLT_CODE_DIR
      - pip install -e ".[gpu]"
      - pip list
      - set +x && [ -f .env ] && set -a && . ./.env && set +a || true && set -x
      - export AZURE_STORAGE_ROOT=$${AZURE_STORAGE_ROOT:-/mnt/data/v-yinyueqin/projects/mulif}
      - export HF_HOME=$${HF_HOME:-$$AZURE_STORAGE_ROOT/hf_home}
      - export HF_CACHE_DIR=$${HF_CACHE_DIR:-$$AZURE_STORAGE_ROOT/hf_cache}
      - export DATA_DIR=$${DATA_DIR:-$$AZURE_STORAGE_ROOT/verl_data}
      - export RUN_LOG_DIR=$${RUN_LOG_DIR:-$$AZURE_STORAGE_ROOT/logs/IFTrain_linear_base_pairwise_alpha1_qwen17b_sft1}
      - export WANDB_DIR=$${WANDB_DIR:-$$AZURE_STORAGE_ROOT/wandb}
      - export RESUME_MODE=$${RESUME_MODE:-auto}
      - export RESUME_FROM_PATH=$${RESUME_FROM_PATH:-null}
      - mkdir -p $$AZURE_STORAGE_ROOT $$HF_HOME $$HF_CACHE_DIR $$DATA_DIR $$RUN_LOG_DIR $$WANDB_DIR
      - set +x && [ -n "$$HF_TOKEN" ] && huggingface-cli login --token $$HF_TOKEN || true && set -x
      # - python hf_data_download.py
      # - python hf_model_download.py
      - bash recipe/mulif_ms/IFTrain_linear_base_pairwise_alpha1_qwen17b_sft1.sh
    submit_args:
      env:
        DATASET_MOUNT_BLOCK_BASED_CACHE_ENABLED: True
        SHARED_MEMORY_PERCENT: 0.5
